name: Daily Commit

on:
  schedule:
    - cron: '25 4 * * *'  # Runs every day at 04:25 UTC
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add dummy commit - 23f2003918@ds.study.iitm.ac.in
        run: |
          date > date.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add date.txt
          git commit -m "Daily update $(date)"
          git push
